//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Tests.SI.Products {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Topicos.AdventureWorks.Wcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SI.Products.IAdventureWorksProducts")]
    public interface IAdventureWorksProducts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksProducts/ListarProductosPorRangoDePrecio", ReplyAction="http://tempuri.org/IAdventureWorksProducts/ListarProductosPorRangoDePrecioRespons" +
            "e")]
        System.Collections.Generic.List<Topicos.AdventureWorks.Model.Product> ListarProductosPorRangoDePrecio(decimal precioInferior, decimal precioSuperior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksProducts/ListarProductosPorRangoDePrecio", ReplyAction="http://tempuri.org/IAdventureWorksProducts/ListarProductosPorRangoDePrecioRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Topicos.AdventureWorks.Model.Product>> ListarProductosPorRangoDePrecioAsync(decimal precioInferior, decimal precioSuperior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksProducts/GetData", ReplyAction="http://tempuri.org/IAdventureWorksProducts/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksProducts/GetData", ReplyAction="http://tempuri.org/IAdventureWorksProducts/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksProducts/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureWorksProducts/GetDataUsingDataContractResponse")]
        AdventureWorks.Tests.SI.Products.CompositeType GetDataUsingDataContract(AdventureWorks.Tests.SI.Products.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksProducts/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureWorksProducts/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AdventureWorks.Tests.SI.Products.CompositeType> GetDataUsingDataContractAsync(AdventureWorks.Tests.SI.Products.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdventureWorksProductsChannel : AdventureWorks.Tests.SI.Products.IAdventureWorksProducts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdventureWorksProductsClient : System.ServiceModel.ClientBase<AdventureWorks.Tests.SI.Products.IAdventureWorksProducts>, AdventureWorks.Tests.SI.Products.IAdventureWorksProducts {
        
        public AdventureWorksProductsClient() {
        }
        
        public AdventureWorksProductsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdventureWorksProductsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksProductsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksProductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Topicos.AdventureWorks.Model.Product> ListarProductosPorRangoDePrecio(decimal precioInferior, decimal precioSuperior) {
            return base.Channel.ListarProductosPorRangoDePrecio(precioInferior, precioSuperior);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Topicos.AdventureWorks.Model.Product>> ListarProductosPorRangoDePrecioAsync(decimal precioInferior, decimal precioSuperior) {
            return base.Channel.ListarProductosPorRangoDePrecioAsync(precioInferior, precioSuperior);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AdventureWorks.Tests.SI.Products.CompositeType GetDataUsingDataContract(AdventureWorks.Tests.SI.Products.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AdventureWorks.Tests.SI.Products.CompositeType> GetDataUsingDataContractAsync(AdventureWorks.Tests.SI.Products.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
