//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Estacionamientoes = new HashSet<Estacionamiento>();
        }
    
        public decimal IDVehiculo { get; set; }
        public Nullable<decimal> Placa { get; set; }
        public Nullable<decimal> Ano { get; set; }
        public Nullable<decimal> IDTipoVehiculo { get; set; }
        public Nullable<decimal> IDFabricante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estacionamiento> Estacionamientoes { get; set; }
        public virtual Fabricante Fabricante { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
