//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiasFeriadosAnuale
    {
        public decimal IdDiaFeriado { get; set; }
        public Nullable<decimal> MesFeriado { get; set; }
        public Nullable<decimal> DiaFeriado { get; set; }
        public string NombreFeriado { get; set; }
    }
}
