
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Topicos.AdventureWorks.Model
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
[DataContract] public partial class ProductProductPhoto
{

    [DataMember] public int ProductID { get; set; }

    [DataMember] public int ProductPhotoID { get; set; }

    [DataMember] public bool Primary { get; set; }

    [DataMember] public System.DateTime ModifiedDate { get; set; }



    public virtual Product Product { get; set; }

    public virtual ProductPhoto ProductPhoto { get; set; }

}

}
