//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea2_WCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamenAnalisisEntities : DbContext
    {
        public ExamenAnalisisEntities()
            : base("name=ExamenAnalisisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Continente> Continentes { get; set; }
        public virtual DbSet<DiasFeriadosAnuale> DiasFeriadosAnuales { get; set; }
        public virtual DbSet<Distrito> Distritoes { get; set; }
        public virtual DbSet<Estacionamiento> Estacionamientoes { get; set; }
        public virtual DbSet<Fabricante> Fabricantes { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Parqueo> Parqueos { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<RegionContinente> RegionContinentes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculoes { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    }
}
