//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taerita2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pai
    {
        public Pai()
        {
            this.Fabricantes = new HashSet<Fabricante>();
        }
    
        public decimal IDPais { get; set; }
        public string NombrePais { get; set; }
        public string AbreviaturaPais { get; set; }
        public Nullable<decimal> IDRegionContinente { get; set; }
    
        public virtual ICollection<Fabricante> Fabricantes { get; set; }
        public virtual RegionContinente RegionContinente { get; set; }
    }
}
