//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taerita2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parqueo
    {
        public Parqueo()
        {
            this.Estacionamientoes = new HashSet<Estacionamiento>();
        }
    
        public decimal IDParqueo { get; set; }
        public Nullable<decimal> ConsecutivoDistrito { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual ICollection<Estacionamiento> Estacionamientoes { get; set; }
    }
}
