//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taerita2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Cantons = new HashSet<Canton>();
        }
    
        public decimal IDProvincia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Canton> Cantons { get; set; }
    }
}
